name: "mydealz2rss"
description: "Scrapes all deals from mydealz.de main page every 10 minutes and publishes them at `<your_ha_instance>/local/mydealz.xml` in RSS format."
version: "0.0.10"
slug: "mydealz2rss"
image: "ghcr.io/dm82m/mydealz2rss-{arch}"
init: false
arch:
  - aarch64
  - amd64
map:
  - type: homeassistant_config
    read_only: False
