name: "NZB-Monkey-Go"
description: "App for Home Assistant to use NZB-Monkey-Go inside of Home Assistant with an easy to use UI."
version: "0.0.2"
slug: "nzb-monkey-go"
image: "ghcr.io/dm82m/nzb-monkey-go-{arch}"
arch:
  - aarch64
  - amd64
map:
  - type: addon_config
    read_only: False
ingress: true
ingress_port: 8501
panel_icon: "mdi:language-go"
panel_title: "NZB-Monkey-Go"
init: false
