name: "Resol-VBus"
description: "Will run json-live-data-server as App in HAOS"
version: "0.0.10"
slug: "resol-vbus"
image: "ghcr.io/dm82m/resol-vbus-{arch}"
init: false
arch:
  - aarch64
  - amd64
ports:
  3333/tcp: 3333
map:
  - type: addon_config
    read_only: False
  - type: homeassistant_config
    read_only: False
uart: true
udev: true
usb: true
