name: Linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  addon-linter:
    name: ğŸ“¦ HA Add-on Linter (${{ matrix.addon }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Hier alle deine Add-on-Ordnernamen eintragen!
        addon: ['mydealz2rss', 'neolink', 'neolink-latest', 'resol-vbus'] 
    steps:
      - name: â¬‡ï¸ Code auschecken
        uses: actions/checkout@v6.0.2

      - name: ğŸš€ Add-on Linter ausfÃ¼hren
        uses: frenck/action-addon-linter@v2.21.0
        with:
          path: "./${{ matrix.addon }}"

  shellcheck:
    name: ğŸš ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Code auschecken
        uses: actions/checkout@v6.0.2
      
      - name: ğŸš ShellCheck ausfÃ¼hren
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './'

  yamllint:
    name: ğŸ“ YAML Lint
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Code auschecken
        uses: actions/checkout@v6.0.2
        
      - name: ğŸ“ yamllint ausfÃ¼hren
        uses: ibiqlik/action-yamllint@v3.1.1